name: Build, push and deploy

on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dictatorbot:${{ github.event.release.tag_name }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - name: deploy to host using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: docker service update --image t0wn/dictatorbot:${{ github.event.release.tag_name }} --env-add VERSION=${{ github.event.release.tag_name }} dictator-bot